# Generated by Django 2.0.7 on 2018-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180727_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
