# Generated by Django 2.0.7 on 2018-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180801_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug1',
        ),
    ]
