# Generated by Django 2.0.7 on 2018-07-25 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_SalesManager',
            new_name='Profile',
        ),
    ]
