# Generated by Django 2.0.7 on 2018-07-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180726_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sale_admin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('salesadmin', 'SALES-ADMIN'), ('salesmanager', 'SALES-MANAGER'), ('salesmen', 'SALESMEN')], max_length=20),
        ),
    ]
