# Generated by Django 2.0.7 on 2018-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180726_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sale_manager',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
