# Generated by Django 2.0.7 on 2018-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sales_manager',
            new_name='sale_manager',
        ),
    ]
