# Generated by Django 2.0.7 on 2018-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180730_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sale_manager',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('salesmanager', 'SALES-MANAGER'), ('salesmen', 'SALESMEN')], max_length=20),
        ),
    ]
