# Generated by Django 2.0.7 on 2018-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180731_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('salesadmin', 'SALES-ADMIN'), ('salesmanager', 'SALES-MANAGER'), ('salesmen', 'SALESMEN')], max_length=20),
        ),
    ]
